"""Добавил теги в отзыв

Revision ID: 55f0c5b4c44c
Revises: 33b002926aa8
Create Date: 2026-09-17 21:48:46.063990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f0c5b4c44c'
down_revision: Union[str, Sequence[str], None] = '33b002926aa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('tags', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'tags')
    # ### end Alembic commands ###
