"""Добавил пользователю поля бюджет, общага

Revision ID: 7123caa9bfb5
Revises: f09be162abea
Create Date: 2026-09-17 17:03:20.942611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7123caa9bfb5'
down_revision: Union[str, Sequence[str], None] = 'f09be162abea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fee_or_budget', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('needs_dormitory', sa.Boolean(), nullable=False))
    op.drop_column('users', 'fee')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fee', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'needs_dormitory')
    op.drop_column('users', 'fee_or_budget')
    # ### end Alembic commands ###
