"""Исправил названия поля

Revision ID: 5097b5c3b229
Revises: 7123caa9bfb5
Create Date: 2026-09-17 17:27:01.002723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5097b5c3b229'
down_revision: Union[str, Sequence[str], None] = '7123caa9bfb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wants_budget', sa.Boolean(), nullable=False))
    op.drop_column('users', 'fee_or_budget')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('fee_or_budget', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'wants_budget')
    # ### end Alembic commands ###
