"""Добавил поля автор, время создания для отзывов и переименовал поле комент в текст

Revision ID: 33b002926aa8
Revises: 58af7bb08075
Create Date: 2026-09-17 21:36:40.283407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b002926aa8'
down_revision: Union[str, Sequence[str], None] = '58af7bb08075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('author', sa.String(length=100), nullable=False))
    op.add_column('reviews', sa.Column('text', sa.String(length=300), nullable=True))
    op.add_column('reviews', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('reviews', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('comment', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'created_at')
    op.drop_column('reviews', 'text')
    op.drop_column('reviews', 'author')
    # ### end Alembic commands ###
