"""users city/ study preferences, fee preferences

Revision ID: ca53c0e24d99
Revises: db89da1a930f
Create Date: 2026-09-16 22:12:29.929060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca53c0e24d99'
down_revision: Union[str, Sequence[str], None] = 'db89da1a930f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('field_of_study', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('fee', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'fee')
    op.drop_column('users', 'field_of_study')
    op.drop_column('users', 'city')
    # ### end Alembic commands ###
