"""Связал таблицу предметов, пользователей и связанную ьаблицу предмет-пользователь

Revision ID: c327b0f87c00
Revises: ca53c0e24d99
Create Date: 2026-09-16 22:36:53.767595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c327b0f87c00'
down_revision: Union[str, Sequence[str], None] = 'ca53c0e24d99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
