"""subjects table

Revision ID: 8e1cff992ad5
Revises: 1df7eaf13638
Create Date: 2026-09-15 22:37:28.279112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1cff992ad5'
down_revision: Union[str, Sequence[str], None] = '1df7eaf13638'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    subjects = sa.table(
        "subjects",
        sa.column("name", sa.String),
    )

    op.bulk_insert(
        subjects,
        [
            {"name": "Русский язык"},
            {"name": "Математика"},
            {"name": "Информатика"},
            {"name": "Физика"},
            {"name": "Химия"},
            {"name": "Биология"},
            {"name": "История"},
            {"name": "Обществознание"},
            {"name": "География"},
            {"name": "Литература"},
            {"name": "Иностранный язык"},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subjects')
    op.execute(
        sa.text("""
                DELETE FROM subjects
                WHERE name IN (
                    'Русский язык',
                    'Математика',
                    'Информатика',
                    'Физика',
                    'Химия',
                    'Биология',
                    'История',
                    'Обществознание',
                    'География',
                    'Литература',
                    'Иностранный язык'
                )
            """)
    )
    # ### end Alembic commands ###
